### ISSUE TITLE
A trailing colon breaks Home Assistant webhooks

### ISSUE THREAD

**Issue by greiginsydney** [chriswein/StreamDeckJSONSender#1]
Hi Christoph,

I've not had any luck sending data from my Stream Deck to a [Home Assistant webhook](https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger) using the StreamDeckJSONSender, but it works fine from the same PC just squirting PowerShell into it.

It looks like having specified a default port of 80 in code.html, the separator is always sent, even if the user provides a blank PORT:

![image](https://user-images.githubusercontent.com/11004787/187310522-5721888d-ab8e-496d-a80c-e792248d46a7.png)

Wireshark reports it sends `http://myHost:8123/api/webhook/send_knx_message:` - with the rogue colon on the end of the line.

I'm about to submit a PR that removes the 80 from `port=80`, and that seems to be all it needs.

I can't figure out how to make a release of the updated code, and I'm hoping that's something you can add please?

<br>

\- Greig.

**Comment by chriswein** [comment]
Yes thats indeed the case! Thank you for pointing it out and your pull request.
